# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/DATA/muon_calibration/muon_calibration_binary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/DATA/muon_calibration/muon_calibration_binary/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/DATA/muon_calibration/muon_calibration_binary/build/CMakeFiles /mnt/DATA/muon_calibration/muon_calibration_binary/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/DATA/muon_calibration/muon_calibration_binary/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named G__CustomClassDictionary

# Build rule for target.
G__CustomClassDictionary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 G__CustomClassDictionary
.PHONY : G__CustomClassDictionary

# fast build rule for target.
G__CustomClassDictionary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/G__CustomClassDictionary.dir/build.make CMakeFiles/G__CustomClassDictionary.dir/build
.PHONY : G__CustomClassDictionary/fast

#=============================================================================
# Target rules for targets named CustomClassDictionary

# Build rule for target.
CustomClassDictionary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CustomClassDictionary
.PHONY : CustomClassDictionary

# fast build rule for target.
CustomClassDictionary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/build
.PHONY : CustomClassDictionary/fast

#=============================================================================
# Target rules for targets named FileReader

# Build rule for target.
FileReader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileReader
.PHONY : FileReader

# fast build rule for target.
FileReader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/build
.PHONY : FileReader/fast

#=============================================================================
# Target rules for targets named CreateTrackTree

# Build rule for target.
CreateTrackTree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CreateTrackTree
.PHONY : CreateTrackTree

# fast build rule for target.
CreateTrackTree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/build
.PHONY : CreateTrackTree/fast

#=============================================================================
# Target rules for targets named Calibrator

# Build rule for target.
Calibrator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Calibrator
.PHONY : Calibrator

# fast build rule for target.
Calibrator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/build
.PHONY : Calibrator/fast

#=============================================================================
# Target rules for targets named ChannelMap

# Build rule for target.
ChannelMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChannelMap
.PHONY : ChannelMap

# fast build rule for target.
ChannelMap/fast:
	$(MAKE) $(MAKESILENT) -f ChannelMap/ChannelMap/CMakeFiles/ChannelMap.dir/build.make ChannelMap/ChannelMap/CMakeFiles/ChannelMap.dir/build
.PHONY : ChannelMap/fast

#=============================================================================
# Target rules for targets named ChannelMap_autogen

# Build rule for target.
ChannelMap_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChannelMap_autogen
.PHONY : ChannelMap_autogen

# fast build rule for target.
ChannelMap_autogen/fast:
	$(MAKE) $(MAKESILENT) -f ChannelMap/ChannelMap/CMakeFiles/ChannelMap_autogen.dir/build.make ChannelMap/ChannelMap/CMakeFiles/ChannelMap_autogen.dir/build
.PHONY : ChannelMap_autogen/fast

#=============================================================================
# Target rules for targets named ChannelMapGenerator

# Build rule for target.
ChannelMapGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChannelMapGenerator
.PHONY : ChannelMapGenerator

# fast build rule for target.
ChannelMapGenerator/fast:
	$(MAKE) $(MAKESILENT) -f ChannelMap/ChannelMapGenerator/CMakeFiles/ChannelMapGenerator.dir/build.make ChannelMap/ChannelMapGenerator/CMakeFiles/ChannelMapGenerator.dir/build
.PHONY : ChannelMapGenerator/fast

#=============================================================================
# Target rules for targets named ChannelMapGenerator_autogen

# Build rule for target.
ChannelMapGenerator_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChannelMapGenerator_autogen
.PHONY : ChannelMapGenerator_autogen

# fast build rule for target.
ChannelMapGenerator_autogen/fast:
	$(MAKE) $(MAKESILENT) -f ChannelMap/ChannelMapGenerator/CMakeFiles/ChannelMapGenerator_autogen.dir/build.make ChannelMap/ChannelMapGenerator/CMakeFiles/ChannelMapGenerator_autogen.dir/build
.PHONY : ChannelMapGenerator_autogen/fast

Calibrator.o: Calibrator.C.o
.PHONY : Calibrator.o

# target to build an object file
Calibrator.C.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/Calibrator.C.o
.PHONY : Calibrator.C.o

Calibrator.i: Calibrator.C.i
.PHONY : Calibrator.i

# target to preprocess a source file
Calibrator.C.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/Calibrator.C.i
.PHONY : Calibrator.C.i

Calibrator.s: Calibrator.C.s
.PHONY : Calibrator.s

# target to generate assembly for a file
Calibrator.C.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/Calibrator.C.s
.PHONY : Calibrator.C.s

CreateTrackTree.o: CreateTrackTree.C.o
.PHONY : CreateTrackTree.o

# target to build an object file
CreateTrackTree.C.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/CreateTrackTree.C.o
.PHONY : CreateTrackTree.C.o

CreateTrackTree.i: CreateTrackTree.C.i
.PHONY : CreateTrackTree.i

# target to preprocess a source file
CreateTrackTree.C.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/CreateTrackTree.C.i
.PHONY : CreateTrackTree.C.i

CreateTrackTree.s: CreateTrackTree.C.s
.PHONY : CreateTrackTree.s

# target to generate assembly for a file
CreateTrackTree.C.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/CreateTrackTree.C.s
.PHONY : CreateTrackTree.C.s

FileReader.o: FileReader.cpp.o
.PHONY : FileReader.o

# target to build an object file
FileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/FileReader.cpp.o
.PHONY : FileReader.cpp.o

FileReader.i: FileReader.cpp.i
.PHONY : FileReader.i

# target to preprocess a source file
FileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/FileReader.cpp.i
.PHONY : FileReader.cpp.i

FileReader.s: FileReader.cpp.s
.PHONY : FileReader.s

# target to generate assembly for a file
FileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/FileReader.cpp.s
.PHONY : FileReader.cpp.s

G__CustomClassDictionary.o: G__CustomClassDictionary.cxx.o
.PHONY : G__CustomClassDictionary.o

# target to build an object file
G__CustomClassDictionary.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/G__CustomClassDictionary.cxx.o
.PHONY : G__CustomClassDictionary.cxx.o

G__CustomClassDictionary.i: G__CustomClassDictionary.cxx.i
.PHONY : G__CustomClassDictionary.i

# target to preprocess a source file
G__CustomClassDictionary.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/G__CustomClassDictionary.cxx.i
.PHONY : G__CustomClassDictionary.cxx.i

G__CustomClassDictionary.s: G__CustomClassDictionary.cxx.s
.PHONY : G__CustomClassDictionary.s

# target to generate assembly for a file
G__CustomClassDictionary.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/G__CustomClassDictionary.cxx.s
.PHONY : G__CustomClassDictionary.cxx.s

src/BinaryDataStructs.o: src/BinaryDataStructs.cpp.o
.PHONY : src/BinaryDataStructs.o

# target to build an object file
src/BinaryDataStructs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/BinaryDataStructs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/BinaryDataStructs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/BinaryDataStructs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/BinaryDataStructs.cpp.o
.PHONY : src/BinaryDataStructs.cpp.o

src/BinaryDataStructs.i: src/BinaryDataStructs.cpp.i
.PHONY : src/BinaryDataStructs.i

# target to preprocess a source file
src/BinaryDataStructs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/BinaryDataStructs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/BinaryDataStructs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/BinaryDataStructs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/BinaryDataStructs.cpp.i
.PHONY : src/BinaryDataStructs.cpp.i

src/BinaryDataStructs.s: src/BinaryDataStructs.cpp.s
.PHONY : src/BinaryDataStructs.s

# target to generate assembly for a file
src/BinaryDataStructs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/BinaryDataStructs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/BinaryDataStructs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/BinaryDataStructs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/BinaryDataStructs.cpp.s
.PHONY : src/BinaryDataStructs.cpp.s

src/ChannelEntry.o: src/ChannelEntry.cpp.o
.PHONY : src/ChannelEntry.o

# target to build an object file
src/ChannelEntry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/ChannelEntry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/ChannelEntry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/ChannelEntry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/ChannelEntry.cpp.o
.PHONY : src/ChannelEntry.cpp.o

src/ChannelEntry.i: src/ChannelEntry.cpp.i
.PHONY : src/ChannelEntry.i

# target to preprocess a source file
src/ChannelEntry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/ChannelEntry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/ChannelEntry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/ChannelEntry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/ChannelEntry.cpp.i
.PHONY : src/ChannelEntry.cpp.i

src/ChannelEntry.s: src/ChannelEntry.cpp.s
.PHONY : src/ChannelEntry.s

# target to generate assembly for a file
src/ChannelEntry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/ChannelEntry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/ChannelEntry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/ChannelEntry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/ChannelEntry.cpp.s
.PHONY : src/ChannelEntry.cpp.s

src/PSDmuonTracker.o: src/PSDmuonTracker.cpp.o
.PHONY : src/PSDmuonTracker.o

# target to build an object file
src/PSDmuonTracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/PSDmuonTracker.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/PSDmuonTracker.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/PSDmuonTracker.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/PSDmuonTracker.cpp.o
.PHONY : src/PSDmuonTracker.cpp.o

src/PSDmuonTracker.i: src/PSDmuonTracker.cpp.i
.PHONY : src/PSDmuonTracker.i

# target to preprocess a source file
src/PSDmuonTracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/PSDmuonTracker.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/PSDmuonTracker.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/PSDmuonTracker.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/PSDmuonTracker.cpp.i
.PHONY : src/PSDmuonTracker.cpp.i

src/PSDmuonTracker.s: src/PSDmuonTracker.cpp.s
.PHONY : src/PSDmuonTracker.s

# target to generate assembly for a file
src/PSDmuonTracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/PSDmuonTracker.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/PSDmuonTracker.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/PSDmuonTracker.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/PSDmuonTracker.cpp.s
.PHONY : src/PSDmuonTracker.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomClassDictionary.dir/build.make CMakeFiles/CustomClassDictionary.dir/src/test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileReader.dir/build.make CMakeFiles/FileReader.dir/src/test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CreateTrackTree.dir/build.make CMakeFiles/CreateTrackTree.dir/src/test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Calibrator.dir/build.make CMakeFiles/Calibrator.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ChannelMapGenerator_autogen"
	@echo "... ChannelMap_autogen"
	@echo "... G__CustomClassDictionary"
	@echo "... Calibrator"
	@echo "... ChannelMap"
	@echo "... ChannelMapGenerator"
	@echo "... CreateTrackTree"
	@echo "... CustomClassDictionary"
	@echo "... FileReader"
	@echo "... Calibrator.o"
	@echo "... Calibrator.i"
	@echo "... Calibrator.s"
	@echo "... CreateTrackTree.o"
	@echo "... CreateTrackTree.i"
	@echo "... CreateTrackTree.s"
	@echo "... FileReader.o"
	@echo "... FileReader.i"
	@echo "... FileReader.s"
	@echo "... G__CustomClassDictionary.o"
	@echo "... G__CustomClassDictionary.i"
	@echo "... G__CustomClassDictionary.s"
	@echo "... src/BinaryDataStructs.o"
	@echo "... src/BinaryDataStructs.i"
	@echo "... src/BinaryDataStructs.s"
	@echo "... src/ChannelEntry.o"
	@echo "... src/ChannelEntry.i"
	@echo "... src/ChannelEntry.s"
	@echo "... src/PSDmuonTracker.o"
	@echo "... src/PSDmuonTracker.i"
	@echo "... src/PSDmuonTracker.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

